inherit_from: .rubocop_todo.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/schema.rb