# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ddecc4f828badf2235c260e89ff76e99c0cf98c8eb433c53739b0dbc19bad87d5dcf2a122c517cce6362755935f91b7dc25dda93dbb11a9ec1776338d7addf2

test:
  secret_key_base: ca874b9b176e83c8d2233de3e47a6cfb890ad53460c13b735887f52054edf8d71aa2b5c0384a0bdae3ce1384a03d8867c396c38fa8b165ecb822a4926a926fe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
